const {createClient}=require("@supabase/supabase-js");
const {spawn}=require("node:child_process");const fs=require("node:fs/promises");const path=require("node:path");const os=require("node:os");
const {resolveRemoteAssets}=require("./asset-resolver");const {uploadRender}=require("./storage-upload");const {overlayFilters}=require("./ad-overlay");
const s=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY), W=process.env.WORKER_ID||`renderer-${process.pid}`, B=process.env.RENDER_OUTPUT_BUCKET||"render-outputs";
async function claim(){const {data,error}=await s.rpc("claim_render_job",{p_worker_id:W,p_lease_seconds:Number(process.env.LEASE_SECONDS||600)});if(error)throw error;return data?.[0]||null}
async function prog(id,stage,p,msg){await s.from("render_jobs").update({stage,progress:p}).eq("id",id);await s.from("render_events").insert({render_job_id:id,stage,progress:p,message:msg})}
function ff(args){return new Promise((ok,no)=>{const p=spawn("ffmpeg",args,{stdio:["ignore","ignore","pipe"]});let e="";p.stderr.on("data",d=>e+=d);p.on("error",no);p.on("close",c=>c===0?ok():no(new Error(`FFMPEG_EXIT_${c}: ${e.slice(-2000)}`)))})}
async function fail(j,e){const retry=Number(j.attempts||1)<Number(process.env.MAX_ATTEMPTS||3);await s.from("render_jobs").update({status:retry?"queued":"failed",stage:retry?"preparing":"failed",error_code:"RENDER_FAILED",error_message:String(e.message||e).slice(0,2000),worker_id:retry?null:W,lease_expires_at:null}).eq("id",j.id)}
async function process(j){const d=await fs.mkdtemp(path.join(os.tmpdir(),"picbo-ad-"));try{const m=j.input_manifest||{};if(Number(m.durationMs)!==15000)throw Error("AD_DURATION_MUST_BE_15_SECONDS");await prog(j.id,"preparing",5,"Preparing 15-second ad");const a=await resolveRemoteAssets(m.assets||[],d);if(!a.length)throw Error("NO_RENDER_ASSETS");const scenes=[];for(let i=0;i<a.length;i++){const x=m.scenes?.[i]||{durationMs:3000,motion:"zoom-in"};const o=path.join(d,`scene-${i}.mp4`),sec=Math.max(.5,Number(x.durationMs||3000)/1000),dim=m.aspect==="16:9"?"1920:1080":m.aspect==="1:1"?"1080:1080":m.aspect==="4:5"?"1080:1350":"1080:1920",z=x.motion==="zoom-out"?"if(lte(on,1),1.12,max(zoom-0.0015,1))":"min(zoom+0.0015,1.12)",vf=`scale=${dim}:force_original_aspect_ratio=increase,crop=${dim},zoompan=z='${z}':d=${Math.round(sec*30)}:s=${dim}:fps=30`;await ff(["-y","-loop","1","-i",a[i].localPath,"-t",String(sec),"-vf",vf,"-r","30","-c:v","libx264","-pix_fmt","yuv420p","-an",o]);scenes.push(o);await prog(j.id,"compositing",10+Math.round((i+1)/a.length*45),`Scene ${i+1}/${a.length}`)}const list=path.join(d,"concat.txt");await fs.writeFile(list,scenes.map(p=>`file '${p.replace(/'/g,"'\\\\''")}'`).join("\n")+"\n");const base=path.join(d,"base.mp4");await ff(["-y","-f","concat","-safe","0","-i",list,"-t","15","-c","copy","-movflags","+faststart",base]);const final=path.join(d,"final.mp4"),filters=overlayFilters(m.overlays||[]);let args=["-y","-i",base];if(filters.length)args.push("-vf",filters.join(","));args.push("-t","15","-r","30","-c:v","libx264","-pix_fmt","yuv420p","-c:a","aac","-movflags","+faststart",final);await prog(j.id,"encoding",70,"Applying ad overlays");await ff(args);const sp=`${j.workspace_id}/${j.video_project_id}/${j.id}/ad-15s.mp4`;await prog(j.id,"uploading",90,"Uploading finished ad");await uploadRender(s,B,sp,final,"video/mp4");const st=await fs.stat(final);await s.from("render_media").insert({render_job_id:j.id,workspace_id:j.workspace_id,kind:"video",storage_path:sp,mime_type:"video/mp4",size_bytes:st.size,duration_ms:15000,metadata:{type:"15_second_ad",aspect:m.aspect||"9:16"}});await s.from("render_jobs").update({status:"completed",stage:"completed",progress:100,output_storage_path:sp,output_mime_type:"video/mp4",output_size_bytes:st.size,completed_at:new Date().toISOString(),worker_id:W,lease_expires_at:null}).eq("id",j.id)}catch(e){await fail(j,e)}finally{await fs.rm(d,{recursive:true,force:true})}}
async function main(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error("WORKER_SECRETS_MISSING");for(;;){try{const j=await claim();if(j)await process(j);else await new Promise(r=>setTimeout(r,Number(process.env.POLL_MS||3000)))}catch(e){console.error(e);await new Promise(r=>setTimeout(r,3000))}}}main().catch(e=>{console.error(e);process.exit(1)});
