 "use client";
import {useEffect,useState,Suspense} from "react";import {useSearchParams} from "next/navigation";import {AppShell} from "@/components/app-shell";
const platforms=[["meta_feed","Meta Feed"],["instagram_feed","Instagram Feed"],["instagram_story","Instagram Story"],["instagram_reel","Instagram Reel"],["tiktok","TikTok"],["youtube_shorts","YouTube Shorts"],["google_display","Google Display"],["linkedin","LinkedIn"]];
export default function AdStudioPage(){return <Suspense fallback={null}><AdStudio/></Suspense>}
function AdStudio(){const searchParams=useSearchParams();const [products,setProducts]=useState<any[]>([]);const [productId,setProductId]=useState("");const [objective,setObjective]=useState("sales");const [selected,setSelected]=useState(["instagram_feed","instagram_story","tiktok"]);const [format,setFormat]=useState("static");const [audience,setAudience]=useState("");const [tone,setTone]=useState("premium and persuasive");const [offer,setOffer]=useState("");const [hook,setHook]=useState("");const [cta,setCta]=useState("Shop Now");const [variants,setVariants]=useState(6);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [templateName,setTemplateName]=useState("");
useEffect(()=>{fetch("/api/products").then(r=>r.json()).then(x=>setProducts(x.products||[]))},[]);
useEffect(()=>{const templateId=searchParams.get("template");if(!templateId)return;fetch(`/api/templates/${templateId}`).then(r=>r.json()).then(x=>{const d=x.template?.definition;if(!d)return;setTemplateName(x.template.name);if(d.objective)setObjective(d.objective);if(d.tone)setTone(d.tone);if(d.audience)setAudience(d.audience);if(d.hook)setHook(d.hook);if(d.cta)setCta(d.cta)}).catch(()=>{})},[searchParams]);
function toggle(x:string){setSelected(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x])}
async function create(){setBusy(true);setMsg("Building ad concepts…");try{const r=await fetch("/api/creative/ads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId,objective,platforms:selected,format,audience,tone,offer,hook,cta,variants})});const j=await r.json();setMsg(r.ok?`Ad brief ${j.briefId} created. AI job ${j.jobId} is complete.`:`Error: ${j.error}`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
return <AppShell><div className="content"><div className="eyebrow">PERFORMANCE CREATIVE</div><h1 className="title">Ad Studio</h1><p className="muted">Turn one product into platform-specific ad concepts, copy and creative directions.</p>{templateName&&<div className="notice" style={{marginTop:12}}>Template applied: {templateName}</div>}<div className="grid three" style={{marginTop:22}}><div className="card"><h3>Product & objective</h3><select className="search" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Choose product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><label>Objective<select value={objective} onChange={e=>setObjective(e.target.value)}><option value="sales">Sales</option><option value="leads">Leads</option><option value="traffic">Traffic</option><option value="awareness">Awareness</option><option value="app_installs">App installs</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="static">Static</option><option value="carousel">Carousel</option><option value="story">Story</option><option value="short">Short video</option></select></label></div><div className="card"><h3>Platforms</h3><div className="chips">{platforms.map(([id,label])=><button key={id} className="chip" style={{color:selected.includes(id)?"#fff":"#9aa1b2"}} onClick={()=>toggle(id)}>{selected.includes(id)?"✓ ":""}{label}</button>)}</div><h3 style={{marginTop:20}}>Variants</h3><input type="number" min="1" max="20" value={variants} onChange={e=>setVariants(Math.min(20,Math.max(1,Number(e.target.value))))}/></div><div className="card"><h3>Creative brief</h3><label>Audience<input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="e.g. women 18–34 interested in skincare"/></label><label>Offer<input value={offer} onChange={e=>setOffer(e.target.value)} placeholder="20% off this week"/></label><label>Hook<input value={hook} onChange={e=>setHook(e.target.value)} placeholder="Your preferred hook, optional"/></label><label>CTA<input value={cta} onChange={e=>setCta(e.target.value)}/></label><label>Tone<input value={tone} onChange={e=>setTone(e.target.value)}/></label><button className="btn primary" disabled={!productId||!selected.length||busy} onClick={create}>{busy?"Creating…":"Generate ads"}</button></div></div>{msg&&<div className="notice" style={{marginTop:16}}>{msg}</div>}<div className="grid three" style={{marginTop:16}}><div className="card"><h3>Copy engine</h3><p className="muted">Hooks, headlines, primary text, descriptions and CTAs are generated from the product and objective.</p></div><div className="card"><h3>Platform adaptation</h3><p className="muted">Each platform has its own format and aspect-ratio specification.</p></div><div className="card"><h3>Safety guardrails</h3><p className="muted">The copy prompt avoids fabricated claims, fake testimonials and invented product facts.</p></div></div></div></AppShell>}
